var smf_formSubmitted=!1,lastKeepAliveCheck=(new Date).getTime(),smf_editorArray=[],ua=navigator.userAgent.toLowerCase(),is_opera=ua.indexOf("opera")!=-1,is_opera5=ua.indexOf("opera/5")!=-1||ua.indexOf("opera 5")!=-1,is_opera6=ua.indexOf("opera/6")!=-1||ua.indexOf("opera 6")!=-1,is_opera7=ua.indexOf("opera/7")!=-1||ua.indexOf("opera 7")!=-1,is_opera8=ua.indexOf("opera/8")!=-1||ua.indexOf("opera 8")!=-1,is_opera9=ua.indexOf("opera/9")!=-1||ua.indexOf("opera 9")!=-1,is_opera95=ua.indexOf("opera/9.5")!=
-1||ua.indexOf("opera 9.5")!=-1,is_opera96=ua.indexOf("opera/9.6")!=-1||ua.indexOf("opera 9.6")!=-1,is_opera10=ua.indexOf("opera/9.8")!=-1||ua.indexOf("opera 9.8")!=-1||ua.indexOf("opera/10.")!=-1||ua.indexOf("opera 10.")!=-1||ua.indexOf("version/10.")!=-1,is_opera95up=is_opera95||is_opera96||is_opera10,is_ff=(ua.indexOf("firefox")!=-1||ua.indexOf("iceweasel")!=-1||ua.indexOf("icecat")!=-1||ua.indexOf("shiretoko")!=-1||ua.indexOf("minefield")!=-1)&&!is_opera,is_gecko=ua.indexOf("gecko")!=-1&&!is_opera,
is_chrome=ua.indexOf("chrome")!=-1,is_safari=ua.indexOf("applewebkit")!=-1&&!is_chrome,is_webkit=ua.indexOf("applewebkit")!=-1,is_ie=ua.indexOf("msie")!=-1&&!is_opera,is_ie4=is_ie&&ua.indexOf("msie 4")!=-1,is_ie5=is_ie&&ua.indexOf("msie 5")!=-1,is_ie50=is_ie&&ua.indexOf("msie 5.0")!=-1,is_ie55=is_ie&&ua.indexOf("msie 5.5")!=-1,is_ie5up=is_ie&&!is_ie4,is_ie6=is_ie&&ua.indexOf("msie 6")!=-1,is_ie6up=is_ie5up&&!is_ie55&&!is_ie5,is_ie6down=is_ie6||is_ie5||is_ie4,is_ie7=is_ie&&ua.indexOf("msie 7")!=-1,
is_ie7up=is_ie6up&&!is_ie6,is_ie7down=is_ie7||is_ie6||is_ie5||is_ie4,is_ie8=is_ie&&ua.indexOf("msie 8")!=-1,is_ie8up=is_ie8&&!is_ie7down,is_iphone=ua.indexOf("iphone")!=-1||ua.indexOf("ipod")!=-1,is_android=ua.indexOf("android")!=-1;if(!("getElementById"in document)&&"all"in document)document.getElementById=function(a){return document.all[a]};else if(!("XMLHttpRequest"in window)&&"ActiveXObject"in window)window.XMLHttpRequest=function(){return new ActiveXObject(is_ie5?"Microsoft.XMLHTTP":"MSXML2.XMLHTTP")};
if(!1 in document&&"all"in document)document.getElementsByTagName=function(a){return document.all.tags[a]};if(!("forms"in document))document.forms=document.getElementsByTagName("form");
function getXMLDocument(a,b){if(!window.XMLHttpRequest)return null;var c=new XMLHttpRequest,d=typeof b!="undefined",e=this;if(d)c.onreadystatechange=function(){if(c.readyState==4&&c.responseXML!=null&&c.status==200)b.call?b.call(e,c.responseXML):(e.tmpMethod=b,e.tmpMethod(c.responseXML),delete e.tmpMethod)};c.open("GET",a,d);c.send(null);return c}
function sendXMLDocument(a,b,c){if(!window.XMLHttpRequest)return!1;var d=new window.XMLHttpRequest,e=this;if(typeof c!="undefined")d.onreadystatechange=function(){d.readyState==4&&(d.responseXML!=null&&d.status==200?c.call(e,d.responseXML):c.call(e,!1))};d.open("POST",a,!0);"setRequestHeader"in d&&d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");d.send(b);return!0}String.prototype.oCharsetConversion={from:"",to:""};
String.prototype.php_to8bit=function(){if(smf_charset=="UTF-8"){for(var a,b="",c=0,d=this.length;c<d;c++)a=this.charCodeAt(c),b+=a<128?String.fromCharCode(a):a<2048?String.fromCharCode(192|a>>6)+String.fromCharCode(128|a&63):a<65536?String.fromCharCode(224|a>>12)+String.fromCharCode(128|a>>6&63)+String.fromCharCode(128|a&63):String.fromCharCode(240|a>>18)+String.fromCharCode(128|a>>12&63)+String.fromCharCode(128|a>>6&63)+String.fromCharCode(128|a&63);return b}else if(this.oCharsetConversion.from.length==
0){switch(smf_charset){case "ISO-8859-1":this.oCharsetConversion={from:"\u00a0-\u00ff",to:"\u00a0-\u00ff"};break;case "ISO-8859-2":this.oCharsetConversion={from:"\u00a0\u0104\u02d8\u0141\u00a4\u013d\u015a\u00a7\u00a8\u0160\u015e\u0164\u0179\u00ad\u017d\u017b\u00b0\u0105\u02db\u0142\u00b4\u013e\u015b\u02c7\u00b8\u0161\u015f\u0165\u017a\u02dd\u017e\u017c\u0154\u00c1\u00c2\u0102\u00c4\u0139\u0106\u00c7\u010c\u00c9\u0118\u00cb\u011a\u00cd\u00ce\u010e\u0110\u0143\u0147\u00d3\u00d4\u0150\u00d6\u00d7\u0158\u016e\u00da\u0170\u00dc\u00dd\u0162\u00df\u0155\u00e1\u00e2\u0103\u00e4\u013a\u0107\u00e7\u010d\u00e9\u0119\u00eb\u011b\u00ed\u00ee\u010f\u0111\u0144\u0148\u00f3\u00f4\u0151\u00f6\u00f7\u0159\u016f\u00fa\u0171\u00fc\u00fd\u0163\u02d9",
to:"\u00a0-\u00ff"};break;case "ISO-8859-5":this.oCharsetConversion={from:"\u00a0\u0401-\u040c\u00ad\u040e-\u044f\u2116\u0451-\u045c\u00a7\u045e\u045f",to:"\u00a0-\u00ff"};break;case "ISO-8859-9":this.oCharsetConversion={from:"\u00a0-\u00cf\u011e\u00d1-\u00dc\u0130\u015e\u00df-\u00ef\u011f\u00f1-\u00fc\u0131\u015f\u00ff",to:"\u00a0-\u00ff"};break;case "ISO-8859-15":this.oCharsetConversion={from:"\u00a0-\u00a3\u20ac\u00a5\u0160\u00a7\u0161\u00a9-\u00b3\u017d\u00b5-\u00b7\u017e\u00b9-\u00bb\u0152\u0153\u0178\u00bf-\u00ff",
to:"\u00a0-\u00ff"};break;case "tis-620":this.oCharsetConversion={from:"\u20ac\u2026\u2018\u2019\u201c\u201d\u2022\u2013\u2014\u00a0\u0e01-\u0e3a\u0e3f-\u0e5b",to:"\u0080\u0085\u0091-\u0097\u00a0-\u00da\u00df-\u00fb"};break;case "windows-1251":this.oCharsetConversion={from:"\u0402\u0403\u201a\u0453\u201e\u2026\u2020\u2021\u20ac\u2030\u0409\u2039\u040a\u040c\u040b\u040f\u0452\u2018\u2019\u201c\u201d\u2022\u2013\u2014\u2122\u0459\u203a\u045a\u045c\u045b\u045f\u00a0\u040e\u045e\u0408\u00a4\u0490\u00a6\u00a7\u0401\u00a9\u0404\u00ab-\u00ae\u0407\u00b0\u00b1\u0406\u0456\u0491\u00b5-\u00b7\u0451\u2116\u0454\u00bb\u0458\u0405\u0455\u0457\u0410-\u044f",
to:"\u0080-\u0097\u0099-\u00ff"};break;case "windows-1253":this.oCharsetConversion={from:"\u20ac\u201a\u0192\u201e\u2026\u2020\u2021\u2030\u2039\u2018\u2019\u201c\u201d\u2022\u2013\u2014\u2122\u203a\u00a0\u0385\u0386\u00a3-\u00a9\u00ab-\u00ae\u2015\u00b0-\u00b3\u0384\u00b5-\u00b7\u0388-\u038a\u00bb\u038c\u00bd\u038e-\u03a1\u03a3-\u03ce",to:"\u0080\u0082-\u0087\u0089\u008b\u0091-\u0097\u0099\u009b\u00a0-\u00a9\u00ab-\u00d1\u00d3-\u00fe"};break;case "windows-1255":this.oCharsetConversion={from:"\u20ac\u201a\u0192\u201e\u2026\u2020\u2021\u02c6\u2030\u2039\u2018\u2019\u201c\u201d\u2022\u2013\u2014\u02dc\u2122\u203a\u00a0-\u00a3\u20aa\u00a5-\u00a9\u00d7\u00ab-\u00b9\u00f7\u00bb-\u00bf\u05b0-\u05b9\u05bb-\u05c3\u05f0-\u05f4\u05d0-\u05ea\u200e\u200f",
to:"\u0080\u0082-\u0089\u008b\u0091-\u0099\u009b\u00a0-\u00c9\u00cb-\u00d8\u00e0-\u00fa\u00fd\u00fe"};break;case "windows-1256":this.oCharsetConversion={from:"\u20ac\u067e\u201a\u0192\u201e\u2026\u2020\u2021\u02c6\u2030\u0679\u2039\u0152\u0686\u0698\u0688\u06af\u2018\u2019\u201c\u201d\u2022\u2013\u2014\u06a9\u2122\u0691\u203a\u0153\u200c\u200d\u06ba\u00a0\u060c\u00a2-\u00a9\u06be\u00ab-\u00b9\u061b\u00bb-\u00be\u061f\u06c1\u0621-\u0636\u00d7\u0637-\u063a\u0640-\u0643\u00e0\u0644\u00e2\u0645-\u0648\u00e7-\u00eb\u0649\u064a\u00ee\u00ef\u064b-\u064e\u00f4\u064f\u0650\u00f7\u0651\u00f9\u0652\u00fb\u00fc\u200e\u200f\u06d2",
to:"\u0080-\u00ff"};break;default:this.oCharsetConversion={from:"",to:""}}a=function(a){for(var c="",b=a.charCodeAt(0),a=a.charCodeAt(2);b<=a;b++)c+=String.fromCharCode(b);return c};this.oCharsetConversion.from=this.oCharsetConversion.from.replace(/.\-./g,a);this.oCharsetConversion.to=this.oCharsetConversion.to.replace(/.\-./g,a)}b="";c=d=0;for(a=this.length;c<a;c++)d=this.oCharsetConversion.from.indexOf(this.charAt(c)),b+=d>-1?this.oCharsetConversion.to.charAt(d):this.charCodeAt(c)>127?"&#"+this.charCodeAt(c)+
";":this.charAt(c);return b};String.prototype.php_strtr=function(a,b){return this.replace(RegExp("["+a+"]","g"),function(c){return b.charAt(a.indexOf(c))})};
String.prototype.php_strtolower=function(){return typeof smf_iso_case_folding=="boolean"&&smf_iso_case_folding==!0?this.php_strtr("ABCDEFGHIJKLMNOPQRSTUVWXYZ\u008a\u008c\u008e\u009f\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00c6\u00c7\u00c8\u00c9\u00ca\u00cb\u00cc\u00cd\u00ce\u00cf\u00d0\u00d1\u00d2\u00d3\u00d4\u00d5\u00d6\u00d7\u00d8\u00d9\u00da\u00db\u00dc\u00dd\u00de","abcdefghijklmnopqrstuvwxyz\u009a\u009c\u009e\u00ff\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00e6\u00e7\u00e8\u00e9\u00ea\u00eb\u00ec\u00ed\u00ee\u00ef\u00f0\u00f1\u00f2\u00f3\u00f4\u00f5\u00f6\u00f7\u00f8\u00f9\u00fa\u00fb\u00fc\u00fd\u00fe"):
this.php_strtr("ABCDEFGHIJKLMNOPQRSTUVWXYZ","abcdefghijklmnopqrstuvwxyz")};String.prototype.php_urlencode=function(){return escape(this).replace(/\+/g,"%2b").replace("*","%2a").replace("/","%2f").replace("@","%40")};String.prototype.php_htmlspecialchars=function(){return this.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};
String.prototype.php_unhtmlspecialchars=function(){return this.replace(/&quot;/g,'"').replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&amp;/g,"&")};String.prototype.php_addslashes=function(){return this.replace(/\\/g,"\\\\").replace(/'/g,"\\'")};String.prototype._replaceEntities=function(a,b,c){return String.fromCharCode(parseInt(c))};String.prototype.removeEntities=function(){return this.replace(/&(amp;)?#(\d+);/g,this._replaceEntities)};
String.prototype.easyReplace=function(a){var b=this,c;for(c in a)b=b.replace(RegExp("%"+c+"%","g"),a[c]);return b};function reqWin(a,b,c,d){b&&self.screen.availWidth*0.8<b||c&&self.screen.availHeight*0.8<c?(d=!1,b=Math.min(b,self.screen.availWidth*0.8),c=Math.min(c,self.screen.availHeight*0.8)):d=typeof d=="boolean"&&d==!0;window.open(a,"requested_popup","toolbar=no,location=no,status=no,menubar=no,scrollbars="+(d?"no":"yes")+",width="+(b?b:480)+",height="+(c?c:220)+",resizable=no");return!1}
function storeCaret(a){if("createTextRange"in a)a.caretPos=document.selection.createRange().duplicate()}
function replaceText(a,b){if("caretPos"in b&&"createTextRange"in b){var c=b.caretPos;c.text=c.text.charAt(c.text.length-1)==" "?a+" ":a;c.select()}else if("selectionStart"in b){var c=b.value.substr(0,b.selectionStart),d=b.value.substr(b.selectionEnd),e=b.scrollTop;b.value=c+a+d;b.setSelectionRange&&(b.focus(),d=is_opera?a.match(/\n/g).length:0,b.setSelectionRange(c.length+a.length+d,c.length+a.length+d));b.scrollTop=e}else b.value+=a,b.focus(b.value.length-1)}
function surroundText(a,b,c){if("caretPos"in c&&"createTextRange"in c){var d=c.caretPos,e=d.text.length;d.text=d.text.charAt(d.text.length-1)==" "?a+d.text+b+" ":a+d.text+b;e==0?(d.moveStart("character",-b.length),d.moveEnd("character",-b.length),d.select()):c.focus(d)}else if("selectionStart"in c){var f=c.value.substr(0,c.selectionStart),d=c.value.substr(c.selectionStart,c.selectionEnd-c.selectionStart),g=c.value.substr(c.selectionEnd),e=c.selectionStart,h=c.scrollTop;c.value=f+a+d+b+g;c.setSelectionRange&&
(f=is_opera?a.match(/\n/g).length:0,g=is_opera?(a+b).match(/\n/g).length:0,d.length==0?c.setSelectionRange(e+a.length+f,e+a.length+f):c.setSelectionRange(e,e+a.length+d.length+b.length+g),c.focus());c.scrollTop=h}else c.value+=a+b,c.focus(c.value.length-1)}function isEmptyText(a){for(a=a.value;a.length>0&&(a.charAt(0)==" "||a.charAt(0)=="\t");)a=a.substring(1,a.length);for(;a.length>0&&(a.charAt(a.length-1)==" "||a.charAt(a.length-1)=="\t");)a=a.substring(0,a.length-1);return a==""?!0:!1}
function submitonce(){smf_formSubmitted=!0;for(var a=0;a<smf_editorArray.length;a++)smf_editorArray[a].doSubmit()}function submitThisOnce(a){if(is_safari)return!smf_formSubmitted;var a=("form"in a?a.form:a).getElementsByTagName("textarea"),b=0,c=a.length;for(;b<c;b++)a[b].readOnly=!0;return!smf_formSubmitted}function setInnerHTML(a,b){a.innerHTML=b}function getInnerHTML(a){return a.innerHTML}
function setOuterHTML(a,b){if("outerHTML"in a)a.outerHTML=b;else{var c=document.createRange();c.setStartBefore(a);a.parentNode.replaceChild(c.createContextualFragment(b),a)}}function in_array(a,b){for(var c in b)if(b[c]==a)return!0;return!1}function array_search(a,b){for(var c in b)if(b[c]==a)return c;return null}function selectRadioByName(a,b){if(!("length"in a))return a.checked=!0;for(var c=0,d=a.length;c<d;c++)if(a[c].value==b)return a[c].checked=!0;return!1}
function invertAll(a,b,c,d){for(var e=0;e<b.length;e++)if("name"in b[e]&&!(typeof c=="string"&&b[e].name.substr(0,c.length)!=c&&b[e].id.substr(0,c.length)!=c)&&(!b[e].disabled||typeof d=="boolean"&&d))b[e].checked=a.checked}lastKeepAliveCheck=(new Date).getTime();
function smf_sessionKeepAlive(){var a=(new Date).getTime();if(smf_scripturl&&a-lastKeepAliveCheck>9E5)(new Image).src=smf_prepareScriptUrl(smf_scripturl)+"action=keepalive;time="+a,lastKeepAliveCheck=a;window.setTimeout("smf_sessionKeepAlive();",12E5)}window.setTimeout("smf_sessionKeepAlive();",12E5);
function smf_setThemeOption(a,b,c,d,e,f){d==null&&(d=smf_session_id);typeof e=="undefined"&&(e="sesc");f==null&&(f="");(new Image).src=smf_prepareScriptUrl(smf_scripturl)+"action=jsoption;var="+a+";val="+b+";"+e+"="+d+f+(c==null?"":"&th="+c)+";time="+(new Date).getTime()}
function smf_avatarResize(){for(var a=document.getElementsByTagName("img"),b=0;b<a.length;b++){var c=[];j=0;if(a[b].className=="avatar")c[j]=new Image,c[j].avatar=a[b],c[j].onload=function(){this.avatar.width=this.width;this.avatar.height=this.height;if(smf_avatarMaxWidth!=0&&this.width>smf_avatarMaxWidth)this.avatar.height=smf_avatarMaxWidth*this.height/this.width,this.avatar.width=smf_avatarMaxWidth;if(smf_avatarMaxHeight!=0&&this.avatar.height>smf_avatarMaxHeight)this.avatar.width=smf_avatarMaxHeight*
this.avatar.width/this.avatar.height,this.avatar.height=smf_avatarMaxHeight},c[j].src=a[b].src,j++}typeof window_oldAvatarOnload!="undefined"&&window_oldAvatarOnload&&(window_oldAvatarOnload(),window_oldAvatarOnload=null)}
function hashLoginPassword(a,b){b==null&&(b=smf_session_id);if(typeof hex_sha1!="undefined"&&a.user.value.indexOf("@")==-1){if(!("opera"in window))a.passwrd.autocomplete="off";a.hash_passwrd.value=hex_sha1(hex_sha1(a.user.value.php_to8bit().php_strtolower()+a.passwrd.value.php_to8bit())+b);a.passwrd.value=is_ff!=-1?"":a.passwrd.value.replace(/./g,"*")}}
function hashAdminPassword(a,b,c){c==null&&(c=smf_session_id);if(typeof hex_sha1!="undefined")a.admin_hash_pass.value=hex_sha1(hex_sha1(b.php_to8bit().php_strtolower()+a.admin_pass.value.php_to8bit())+c),a.admin_pass.value=a.admin_pass.value.replace(/./g,"*")}
function expandPages(a,b,c,d,e){var f="",g=0;a.style.fontWeight="normal";a.onclick="";(d-c)/e>50&&(g=d,d=c+50*e);for(;c<d;c+=e)f+='<a class="navPages" href="'+b.replace(/%1\$d/,c).replace(/%%/g,"%")+'">'+(1+c/e)+"</a> ";g>0&&(f+='<span style="font-weight: bold; cursor: '+(is_ie&&!is_ie6up?"hand":"pointer")+';" onclick="expandPages(this, \''+b+"', "+d+", "+g+", "+e+');"> ... </span> ');setInnerHTML(a,f)}
function smc_preCacheImage(a){if(!("smc_aCachedImages"in window))window.smc_aCachedImages=[];if(!in_array(a,window.smc_aCachedImages))(new Image).src=a}function smc_Cookie(a){this.opt=a;this.oCookies={};this.init()}smc_Cookie.prototype.init=function(){if("cookie"in document&&document.cookie!="")for(var a=document.cookie.split(";"),b=0,c=a.length;b<c;b++){var d=a[b].split("=");this.oCookies[d[0].replace(/^\s+|\s+$/g,"")]=decodeURIComponent(d[1])}};
smc_Cookie.prototype.get=function(a){return a in this.oCookies?this.oCookies[a]:null};smc_Cookie.prototype.set=function(a,b){document.cookie=a+"="+encodeURIComponent(b)};function smc_Toggle(a){this.opt=a;this.bCollapsed=!1;this.oCookie=null;this.init()}
smc_Toggle.prototype.init=function(){if(!("bToggleEnabled"in this.opt)||this.opt.bToggleEnabled){if("oCookieOptions"in this.opt&&this.opt.oCookieOptions.bUseCookie){this.oCookie=new smc_Cookie({});var a=this.oCookie.get(this.opt.oCookieOptions.sCookieName);if(a!=null)this.opt.bCurrentlyCollapsed=a=="1"}this.opt.bCurrentlyCollapsed&&this.changeState(!0,!0);if("aSwapImages"in this.opt)for(var a=0,b=this.opt.aSwapImages.length;a<b;a++){var c=document.getElementById(this.opt.aSwapImages[a].sId);if(typeof c==
"object"&&c!=null){if(c.style.display=="none")c.style.display="";c.instanceRef=this;c.onclick=function(){this.instanceRef.toggle();this.blur()};c.style.cursor="pointer";smc_preCacheImage(this.opt.aSwapImages[a].srcCollapsed)}}if("aSwapLinks"in this.opt){a=0;for(b=this.opt.aSwapLinks.length;a<b;a++)if(c=document.getElementById(this.opt.aSwapLinks[a].sId),typeof c=="object"&&c!=null){if(c.style.display=="none")c.style.display="";c.instanceRef=this;c.onclick=function(){this.instanceRef.toggle();this.blur();
return!1}}}}};
smc_Toggle.prototype.changeState=function(a,b){b=typeof b=="undefined"?!1:!0;if(!b&&a&&"funcOnBeforeCollapse"in this.opt)this.tmpMethod=this.opt.funcOnBeforeCollapse,this.tmpMethod(),delete this.tmpMethod;else if(!b&&!a&&"funcOnBeforeExpand"in this.opt)this.tmpMethod=this.opt.funcOnBeforeExpand,this.tmpMethod(),delete this.tmpMethod;if("aSwapImages"in this.opt)for(var c=0,d=this.opt.aSwapImages.length;c<d;c++){var e=document.getElementById(this.opt.aSwapImages[c].sId);if(typeof e=="object"&&e!=null){var f=
a?this.opt.aSwapImages[c].srcCollapsed:this.opt.aSwapImages[c].srcExpanded;if(e.src!=f)e.src=f;e.alt=e.title=a?this.opt.aSwapImages[c].altCollapsed:this.opt.aSwapImages[c].altExpanded}}if("aSwapLinks"in this.opt){c=0;for(d=this.opt.aSwapLinks.length;c<d;c++)e=document.getElementById(this.opt.aSwapLinks[c].sId),typeof e=="object"&&e!=null&&setInnerHTML(e,a?this.opt.aSwapLinks[c].msgCollapsed:this.opt.aSwapLinks[c].msgExpanded)}c=0;for(d=this.opt.aSwappableContainers.length;c<d;c++)if(this.opt.aSwappableContainers[c]!=
null&&(e=document.getElementById(this.opt.aSwappableContainers[c]),typeof e=="object"&&e!=null))e.style.display=a?"none":"";this.bCollapsed=a;"oCookieOptions"in this.opt&&this.opt.oCookieOptions.bUseCookie&&this.oCookie.set(this.opt.oCookieOptions.sCookieName,this.bCollapsed?"1":"0");"oThemeOptions"in this.opt&&this.opt.oThemeOptions.bUseThemeSettings&&smf_setThemeOption(this.opt.oThemeOptions.sOptionName,this.bCollapsed?"1":"0","sThemeId"in this.opt.oThemeOptions?this.opt.oThemeOptions.sThemeId:
null,this.opt.oThemeOptions.sSessionId,this.opt.oThemeOptions.sSessionVar,"sAdditionalVars"in this.opt.oThemeOptions?this.opt.oThemeOptions.sAdditionalVars:null)};smc_Toggle.prototype.toggle=function(){this.changeState(!this.bCollapsed)};
function createEventListener(a){if(!("addEventListener"in a))a.attachEvent?(a.addEventListener=function(b,c){a.attachEvent("on"+b,c)},a.removeEventListener=function(b,c){a.detachEvent("on"+b,c)}):(a.addEventListener=function(b,c){a["on"+b]=c},a.removeEventListener=function(b){a["on"+b]=null})}
function grabJumpToContent(){var a=getXMLDocument(smf_prepareScriptUrl(smf_scripturl)+"action=xmlhttp;sa=jumpto;xml"),b=[];setBusy(!0);if(a.responseXML)for(var a=a.responseXML.getElementsByTagName("smf")[0].getElementsByTagName("item"),c=0,d=a.length;c<d;c++)b[b.length]={id:parseInt(a[c].getAttribute("id")),isCategory:a[c].getAttribute("type")=="category",name:a[c].firstChild.nodeValue.removeEntities(),is_current:!1,childLevel:parseInt(a[c].getAttribute("childlevel"))};setBusy(!1);c=0;for(d=aJumpTo.length;c<
d;c++)aJumpTo[c].fillSelect(b)}var aJumpTo=[];function JumpTo(a){this.opt=a;this.dropdownList=null;this.showSelect()}
JumpTo.prototype.showSelect=function(){for(var a="",b=this.opt.iCurBoardChildLevel;b>0;b--)a+=this.opt.sBoardChildLevelIndicator;setInnerHTML(document.getElementById(this.opt.sContainerId),this.opt.sJumpToTemplate.replace(/%select_id%/,this.opt.sContainerId+"_select").replace(/%dropdown_list%/,'<select name="'+this.opt.sContainerId+'_select" id="'+this.opt.sContainerId+'_select" '+("implementation"in document?"":'onmouseover="grabJumpToContent();" ')+("onbeforeactivate"in document?"onbeforeactivate":
"onfocus")+'="grabJumpToContent();"><option value="?board='+this.opt.iCurBoardId+'.0">'+a+this.opt.sBoardPrefix+this.opt.sCurBoardName.removeEntities()+'</option></select>&nbsp;<input type="button" value="'+this.opt.sGoButtonLabel+'" onclick="window.location.href = \''+smf_prepareScriptUrl(smf_scripturl)+"board="+this.opt.iCurBoardId+".0';\" />"));this.dropdownList=document.getElementById(this.opt.sContainerId+"_select")};
JumpTo.prototype.fillSelect=function(a){var b=!("implementation"in document),c=0,d=document.createElement("option");d.appendChild(document.createTextNode(this.opt.sCatSeparator));d.disabled="disabled";d.value="";if(b)this.dropdownList.onmouseover=null,this.dropdownList.remove(0);"onbeforeactivate"in document?this.dropdownList.onbeforeactivate=null:this.dropdownList.onfocus=null;for(var e=b?this.dropdownList:document.createDocumentFragment(),f=0,g=a.length;f<g;f++){var h,i;if(!a[f].isCategory&&a[f].id==
this.opt.iCurBoardId)if(b)c=this.dropdownList.options.length;else{this.dropdownList.insertBefore(e,this.dropdownList.options[0]);e=document.createDocumentFragment();continue}if(a[f].isCategory)e.appendChild(d.cloneNode(!0));else for(h=a[f].childLevel,i="";h>0;h--)i+=this.opt.sBoardChildLevelIndicator;h=document.createElement("option");h.appendChild(document.createTextNode((a[f].isCategory?this.opt.sCatPrefix:i+this.opt.sBoardPrefix)+a[f].name));h.value=a[f].isCategory?"#c"+a[f].id:"?board="+a[f].id+
".0";e.appendChild(h);a[f].isCategory&&e.appendChild(d.cloneNode(!0))}this.dropdownList.appendChild(e);if(b)this.dropdownList.options[c].selected=!0;this.dropdownList.style.width="auto";this.dropdownList.focus();this.dropdownList.onchange=function(){if(this.selectedIndex>0&&this.options[this.selectedIndex].value)window.location.href=smf_scripturl+this.options[this.selectedIndex].value.substr(smf_scripturl.indexOf("?")==-1||this.options[this.selectedIndex].value.substr(0,1)!="?"?0:1)}};
var aIconLists=[];function IconList(a){if(window.XMLHttpRequest){this.opt=a;this.bListLoaded=!1;this.funcMousedownHandler=this.oContainerDiv=null;this.funcParent=this;this.iCurTimeout=this.iCurMessageId=0;if(!("sSessionVar"in this.opt))this.opt.sSessionVar="sesc";this.initIcons()}}
IconList.prototype.initIcons=function(){for(var a=document.images.length-1,b=this.opt.sIconIdPrefix.length;a>=0;a--)document.images[a].id.substr(0,b)==this.opt.sIconIdPrefix&&setOuterHTML(document.images[a],'<div title="'+this.opt.sLabelIconList+'" onclick="'+this.opt.sBackReference+".openPopup(this, "+document.images[a].id.substr(b)+')" onmouseover="'+this.opt.sBackReference+'.onBoxHover(this, true)" onmouseout="'+this.opt.sBackReference+'.onBoxHover(this, false)" style="background: '+this.opt.sBoxBackground+
"; cursor: "+(is_ie&&!is_ie6up?"hand":"pointer")+'; padding: 0px; text-align: center;"><img src="'+document.images[a].src+'" alt="'+document.images[a].alt+'" id="'+document.images[a].id+'" style="margin:0; padding: 0;" /></div>')};IconList.prototype.onBoxHover=function(a,b){a.style.border=b?this.opt.iBoxBorderWidthHover+"px solid "+this.opt.sBoxBorderColorHover:"";a.style.background=b?this.opt.sBoxBackgroundHover:this.opt.sBoxBackground;a.style.padding=b?3-this.opt.iBoxBorderWidthHover+"px":"3px"};
IconList.prototype.openPopup=function(a,b){this.iCurMessageId=b;if(!this.bListLoaded&&this.oContainerDiv==null)this.oContainerDiv=document.createElement("div"),this.oContainerDiv.id="iconList",this.oContainerDiv.style.display="none",this.oContainerDiv.style.cursor=is_ie&&!is_ie6up?"hand":"pointer",this.oContainerDiv.style.position="absolute",this.oContainerDiv.style.width=a.offsetWidth+"px",this.oContainerDiv.style.background=this.opt.sContainerBackground,this.oContainerDiv.style.border=this.opt.sContainerBorder,
this.oContainerDiv.style.padding="0px",this.oContainerDiv.style.textAlign="center",document.body.appendChild(this.oContainerDiv),setBusy(!0),this.tmpMethod=getXMLDocument,this.tmpMethod(smf_prepareScriptUrl(this.opt.sScriptUrl)+"action=xmlhttp;sa=messageicons;board="+this.opt.iBoardId+";xml",this.onIconsReceived),delete this.tmpMethod,createEventListener(document.body);var c=smf_itemPos(a);is_ie50&&(c[1]+=4);this.oContainerDiv.style.top=c[1]+a.offsetHeight+"px";this.oContainerDiv.style.left=c[0]-
1+"px";this.oClickedIcon=a;if(this.bListLoaded)this.oContainerDiv.style.display="block";document.body.addEventListener("mousedown",this.onWindowMouseDown,!1)};
IconList.prototype.onIconsReceived=function(a){for(var a=a.getElementsByTagName("smf")[0].getElementsByTagName("icon"),b="",c=0,d=a.length;c<d;c++)b+='<div onmouseover="'+this.opt.sBackReference+'.onItemHover(this, true)" onmouseout="'+this.opt.sBackReference+'.onItemHover(this, false);" onmousedown="'+this.opt.sBackReference+".onItemMouseDown(this, '"+a[c].getAttribute("value")+'\');" style="padding: 3px 0px 3px 0px; margin-left: auto; margin-right: auto; border: '+this.opt.sItemBorder+"; background: "+
this.opt.sItemBackground+'"><img src="'+a[c].getAttribute("url")+'" alt="'+a[c].getAttribute("name")+'" title="'+a[c].firstChild.nodeValue+'" /></div>';setInnerHTML(this.oContainerDiv,b);this.oContainerDiv.style.display="block";this.bListLoaded=!0;if(is_ie)this.oContainerDiv.style.width=this.oContainerDiv.clientWidth+"px";setBusy(!1)};
IconList.prototype.onItemHover=function(a,b){a.style.background=b?this.opt.sItemBackgroundHover:this.opt.sItemBackground;a.style.border=b?this.opt.sItemBorderHover:this.opt.sItemBorder;this.iCurTimeout!=0&&window.clearTimeout(this.iCurTimeout);if(b)this.onBoxHover(this.oClickedIcon,!0);else this.iCurTimeout=window.setTimeout(this.opt.sBackReference+".collapseList();",500)};
IconList.prototype.onItemMouseDown=function(a,b){if(this.iCurMessageId!=0){setBusy(!0);this.tmpMethod=getXMLDocument;var c=this.tmpMethod(smf_prepareScriptUrl(this.opt.sScriptUrl)+"action=jsmodify;topic="+this.opt.iTopicId+";msg="+this.iCurMessageId+";"+this.opt.sSessionVar+"="+this.opt.sSessionId+";icon="+b+";xml");delete this.tmpMethod;setBusy(!1);c=c.responseXML.getElementsByTagName("smf")[0].getElementsByTagName("message")[0];if(c.getElementsByTagName("error").length==0)this.opt.bShowModify&&
c.getElementsByTagName("modified").length!=0&&setInnerHTML(document.getElementById("modified_"+this.iCurMessageId),c.getElementsByTagName("modified")[0].childNodes[0].nodeValue),this.oClickedIcon.getElementsByTagName("img")[0].src=a.getElementsByTagName("img")[0].src}};IconList.prototype.onWindowMouseDown=function(){for(var a=aIconLists.length-1;a>=0;a--)aIconLists[a].funcParent.tmpMethod=aIconLists[a].collapseList,aIconLists[a].funcParent.tmpMethod(),delete aIconLists[a].funcParent.tmpMethod};
IconList.prototype.collapseList=function(){this.onBoxHover(this.oClickedIcon,!1);this.oContainerDiv.style.display="none";this.iCurMessageId=0;document.body.removeEventListener("mousedown",this.onWindowMouseDown,!1)};
function smf_mousePose(a){var b=0,c=0;a.pageX?(c=a.pageY,b=a.pageX):a.clientX&&(b=a.clientX+(document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft),c=a.clientY+(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop));return[b,c]}
function smf_itemPos(a){var b=0,c=0;if("offsetParent"in a){b=a.offsetLeft;for(c=a.offsetTop;a.offsetParent&&typeof a.offsetParent=="object";)a=a.offsetParent,b+=a.offsetLeft,c+=a.offsetTop}else if("x"in a)b=a.x,c=a.y;return[b,c]}function smf_prepareScriptUrl(a){return a.indexOf("?")==-1?a+"?":a+(a.charAt(a.length-1)=="?"||a.charAt(a.length-1)=="&"||a.charAt(a.length-1)==";"?"":";")}var aOnloadEvents=[];
function addLoadEvent(a){typeof a=="function"&&(!("onload"in window)||typeof window.onload!="function")?window.onload=a:aOnloadEvents.length==0?(aOnloadEvents[0]=window.onload,aOnloadEvents[1]=a,window.onload=function(){for(var a=0,c=aOnloadEvents.length;a<c;a++)if(typeof aOnloadEvents[a]=="function")aOnloadEvents[a]();else typeof aOnloadEvents[a]=="string"&&eval(aOnloadEvents[a])}):aOnloadEvents[aOnloadEvents.length]=a}
function smfFooterHighlight(a,b){a.src=smf_images_url+"/"+(b?"h_":"")+a.id+".gif"}
function smfSelectText(a,b){var c=typeof b=="boolean"&&b?document.getElementById(a):a.parentNode.nextSibling;if(typeof c!="object"||c==null)return!1;if("createTextRange"in document.body){var d=document.body.createTextRange();d.moveToElementText(c);d.select()}else if(window.getSelection)if(d=window.getSelection(),d.setBaseAndExtent){var e=c.lastChild;d.setBaseAndExtent(c,0,e,"innerText"in e?e.innerText.length:e.textContent.length)}else e=document.createRange(),e.selectNodeContents(c),d.removeAllRanges(),
d.addRange(e);return!1}function smc_saveEntities(a,b,c){if(typeof c=="string")for(var d=0,e=document.forms[a].elements.length;d<e;d++)if(document.forms[a].elements[d].id.substr(0,c.length)==c)b[b.length]=document.forms[a].elements[d].name;d=0;for(e=b.length;d<e;d++)if(b[d]in document.forms[a])document.forms[a][b[d]].value=document.forms[a][b[d]].value.replace(/&#/g,"&#38;#")}
function cleanFileInput(a){is_opera||is_ie||is_safari||is_chrome?document.getElementById(a).outerHTML=document.getElementById(a).outerHTML:(document.getElementById(a).type="input",document.getElementById(a).type="file")}
function smf_codeBoxFix(){for(var a=document.getElementsByTagName("code"),b=a.length-1;b>=0;b--)if(is_webkit&&a[b].offsetHeight<20)a[b].style.height=a[b].offsetHeight+20+"px";else if(is_ff&&(a[b].scrollWidth>a[b].clientWidth||a[b].clientWidth==0))a[b].style.overflow="scroll";else if("currentStyle"in a[b]&&a[b].currentStyle.overflow=="auto"&&(a[b].currentStyle.height==""||a[b].currentStyle.height=="auto")&&(a[b].scrollWidth>a[b].clientWidth||a[b].clientWidth==0)&&a[b].offsetHeight!=0)a[b].style.height=
a[b].offsetHeight+24+"px"}(is_ie&&!is_ie4||is_webkit||is_ff)&&addLoadEvent(smf_codeBoxFix);function smc_toggleImageDimensions(){var a=document.getElementsByTagName("IMG");for(oImage in a)if(!(a[oImage].className==void 0||a[oImage].className.indexOf("bbc_img resized")==-1))a[oImage].style.cursor="pointer",a[oImage].onclick=function(){this.style.width=this.style.height=this.style.width=="auto"?null:"auto"}}addLoadEvent(smc_toggleImageDimensions);
function smf_addButton(a,b,c){a=document.getElementById(a);b=a.getElementsByTagName("span");if(b.length>0)b=b[b.length-1],b.className=b.className.replace(/\s*last/,"position_holder");a=a.getElementsByTagName("ul")[0];b=document.createElement("li");setInnerHTML(b,'<a href="'+c.sUrl+'" '+("sCustom"in c?c.sCustom:"")+'><span class="last"'+("sId"in c?' id="'+c.sId+'"':"")+">"+c.sText+"</span></a>");a.appendChild(b)}
var smf_addListItemHoverEvents=function(){for(var a=0;a<document.styleSheets.length;a++)for(var b=0;b<document.styleSheets[a].rules.length;b++)oCssRule=document.styleSheets[a].rules[b],oCssRule.selectorText.indexOf("LI:hover")!=-1&&(sNewSelector=oCssRule.selectorText.replace(/LI:hover/gi,"LI.iehover"),document.styleSheets[a].addRule(sNewSelector,oCssRule.style.cssText));a=document.getElementsByTagName("LI");for(oListItem in a)a[oListItem].onmouseover=function(){this.className+=" iehover"},a[oListItem].onmouseout=
function(){this.className=this.className.replace(/ iehover\b/,"")}};is_ie7down&&"attachEvent"in window&&window.attachEvent("onload",smf_addListItemHoverEvents);function readCookie(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}return null}
function createCookie(a,b,c){if(c){var d=new Date;d.setTime(d.getTime()+c*864E5);c="; expires="+d.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/"}function setTextSize(a){textsize=a;if(textsize<textSizeMin||textsize>textSizeMax)textsize=textSizeDefault;$("body").css("font-size",a+textSizeUnit);createCookie("SMF_textsize",textsize,500);$("#curfontsize").html(textsize+textSizeUnit)}
(function(a){function b(){var b;b=a(this);if(!b.data("timeago")){b.data("timeago",{datetime:e.datetime(b)});var d=a.trim(b.text());d.length>0&&b.attr("title",d)}b=b.data("timeago");isNaN(b.datetime)||a(this).text(c(b.datetime));return this}function c(a){var c=new Date,b=a.getTime()+c.getTimezoneOffset()*6E4,i=c.getTime()-b;c.setHours(0);c.setMinutes(0);c=c.getTime();if(b<c){c-=b;b=c/36E5;if(b>24&&b<144)return e.settings.strings.weekdays[a.getUTCDay()]+", "+d(a.getUTCHours())+":"+d(a.getUTCMinutes());
if(b>0&&b<24)return e.settings.strings.yesterday+", "+d(a.getUTCHours())+":"+d(a.getUTCMinutes())}e.settings.allowFuture=i<0&&Math.abs(i)<36E5?!1:!0;return e.inWords(i)}function d(a){for(a+="";a.length<2;)a="0"+a;return a}a.timeago=function(b){return b instanceof Date?c(b):typeof b==="string"?c(a.timeago.parse(b)):c(a.timeago.datetime(b))};var e=a.timeago;a.extend(a.timeago,{settings:{refreshMillis:6E4,allowFuture:!0},inWords:function(c){function b(e,g){return(a.isFunction(e)?e(g,c):e).replace(/%d/i,
d.numbers&&d.numbers[g]||g)}var d=this.settings.strings,e=d.prefixAgo,o=d.suffixAgo;if(this.settings.allowFuture){if(c<0)e=d.prefixFromNow,o=d.suffixFromNow;c=Math.abs(c)}var k=c/1E3,m=k/60,n=m/60,l=n/24,p=l/365,k=k<45&&b(d.seconds,Math.round(k))||k<90&&b(d.minute,1)||m<45&&b(d.minutes,Math.round(m))||m<90&&b(d.hour,1)||n<24&&b(d.hours,Math.round(n))||n<48&&b(d.day,1)||l<30&&b(d.days,Math.floor(l))||l<60&&b(d.month,1)||l<365&&b(d.months,Math.floor(l/30))||p<2&&b(d.year,1)||b(d.years,Math.floor(p));
return a.trim([e,k,o].join(" "))},parse:function(b){b=a.trim(b);b=b.replace(/\.\d\d\d+/,"");b=b.replace(/-/,"/").replace(/-/,"/");b=b.replace(/T/," ").replace(/Z/," UTC");b=b.replace(/([\+\-]\d\d)\:?(\d\d)/," $1$2");return new Date(b)},datetime:function(b){b=a(b).get(0).tagName.toLowerCase()==="time"?a(b).attr("datetime"):a(b).attr("title");return e.parse(b)}});a.fn.timeago=function(){var a=this;a.each(b);var c=e.settings;c.refreshMillis>0&&setInterval(function(){a.each(b)},c.refreshMillis);return a}})(jQuery);