// Turkish language strings
hs.lang = {
loadingText : "Yükleniyor...",
loadingTitle : "İptal etmek için tıklayın",
focusTitle : "Öne getirmek için tıklayın",
fullExpandTitle : "Gerçek boyutunda görüntüle",
creditsText : "<i>Highslide JS</i> tarafından güçlendirilmiştir",
creditsTitle : "Highslide JS anasayfasına git",
previousText : "Önceki",
nextText : "Sonraki",
moveText : "Sürükle",
closeText : "Kapat",
closeTitle : "Kapat (esc)",
resizeTitle : "Yeniden Boyutlandır",
playText : "Oynat",
playTitle : "Slayt gösterisi başlat (klavye boşluk)",
pauseText : "Durdur",
pauseTitle : "Slayt gösterisini durdur (klavye boşluk)",
previousTitle : "Önceki (klavye sol ok)",
nextTitle : "Sonraki (klavye sağ ok)",
moveTitle : "Sürükle",
fullExpandText : "Gerçek boyut",
number: "%2 Resminin %1 i",
restoreTitle : "Tıklayarak kapatabilir, farenizin sol tuşuna basılı tutarak sürükleyebilir, klavyenizin yön tuşları ile gezinebilirsiniz."
};
