// Dutch language strings
hs.lang = {
loadingText : "Laden...",
loadingTitle : "Klik voor cancel",
focusTitle : "Klik om vooraan te brengen",
fullExpandTitle : "Vergroot naar eigen formaat",
creditsText : "Gemaakt door <i>Highslide JS</i>",
creditsTitle : "Ga naar de Highslide JS website",
previousText : "Vorige",
nextText : "Volgende",
moveText : "Schuif",
closeText : "Sluit",
closeTitle : "Sluit (esc)",
resizeTitle : "Verander maat",
playText : "Speel af",
playTitle : "Speel slideshow af(spatiebalk)",
pauseText : "Pauzeer",
pauseTitle : "Pauzeer slideshow (spatiebalk)",
previousTitle : "Vorige (pijl links)",
nextTitle : "Next (pijl rechts)",
moveTitle : "Schuif",
fullExpandText : "Volledig",
number: "Afbeelding %1 of %2",
restoreTitle : "Klik om Afbeelding te sluiten, klik en sleep om te schuiven. Gebruik pijltoetsen voor vorige en volgende."
};
